id: IFEED9B29
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-02-21T14:18:50+00:00'
last_modified: '2022-06-09T17:49:38.828067+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8043
  title: ཁྲོམ་དགེ་སྒྲུབ་སྒྲོན་མའི་དག་སྣང་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    47D4:
      image_group_id: I3CN8045
      title: Volume 1 of khrom dge sgrub sgron ma'i dag snang sogs/
      total_pages: 392
      order: 1
      base_file: 47D4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
